language: cpp
compiler:
  - gcc
before_install: 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get dist-upgrade
  - sudo apt-get install -y llvm clang cmake libpcap-dev libgmp-dev libmpfr-dev libmpc-dev libc-dev libxml2-dev libboost-all-dev
install: mkdir build && cd build && cmake ../ && make

