before_install: 
  - sudo apt-get -y update
  - sudo apt-get install -y cmake libpcap-dev
  - wget -O boost_1_54_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.gz/download
  - tar -xzf boost_1_54_0.tar.gz
  - cd boost_1_54_0/
  - ./bootstrap.sh --prefix=/usr/local
  - n=$(cat /proc/cpuinfo | grep "cpu cores" | uniq | awk '{print $NF}')
  - sudo ./b2 -d+1 --ver--with=all -j $n install
  - sudo ldconfig
  - cd ../
install: mkdir build && cd build && cmake ../ && make

